### ISSUE TITLE
Only works up to iOS 9 iboot?

### ISSUE THREAD

**Issue by IMS212** [haiyuidesu/iBootPatcher#1]
The readme states this. Is this a mistake?
> I. Requierements
	1. macOS/Linux
	2. basic compilation tools
	3. decrypted 64bit iBoot (iBoot/iBSS/iBEC/LLB) from **iOS 7.x to 9.x**

**Comment by haiyuidesu** [comment]
no you read it well.

the patch applied to the iBoot works only for iOS 7 to 9.

you can also here for the original: https://github.com/axi0mX/ipwndfu
